### ISSUE TITLE
calculate_ctf support Tensors as input

### ISSUE THREAD

**Issue by rsanchezgarc** [teamtomo/libtilt#49]
calculate_ctf  (https://github.com/teamtomo/libtilt/blob/65efd4fbdd262212561651d30d8320a68388623c/src/libtilt/ctf/ctf_2d.py#L12) seems to support Tensors as inputs, but the type hints suggest it only can handle floats.

**Comment by alisterburt** [comment]
ooh good catch! Want to submit a PR or should I fix?

**Comment by rsanchezgarc** [comment]
Happy to do it myself as soon as you give me permissions

**Comment by alisterburt** [comment]
no permissions required for a PR, fork and PR is always available (and my preferred flow for dev) - saying that I'm adding you anyway so you can merge PRs etc :)

**Comment by rsanchezgarc** [comment]
Solved in #50
