### ISSUE TITLE
backproject_fourier.py backproject_fourier(...) do_gridding_correction argument is not used

### ISSUE THREAD

**Issue by rsanchezgarc** [teamtomo/libtilt#51]
The do_gridding_correction is not used in backproject_fourier.backproject_fourier(...)

**Comment by alisterburt** [comment]
ah yes, correction is always applied here
https://github.com/teamtomo/libtilt/blob/65efd4fbdd262212561651d30d8320a68388623c/src/libtilt/backprojection/backproject_fourier.py#L71-L79

good catch - will sort!
